# Generated by Django 2.2.6 on 2019-11-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerHero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('subtitle', models.TextField(verbose_name='Subtitulo')),
                ('buttonlink', models.URLField(verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la persona')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('stars', models.PositiveSmallIntegerField(verbose_name='Estrellas')),
            ],
        ),
    ]
