# Generated by Django 2.2.6 on 2019-11-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20191115_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='tipo',
            field=models.ManyToManyField(related_name='get_type', to='packages.TypePackage', verbose_name='Categoria'),
        ),
    ]
